language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment  -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSIONprokka scikit-learn=0.21.3 numpy scipy biopython
  - conda activate test-environment
  - python3 download_and_set_models.py

script:
  - bash test/all.sh
